# Generated by Django 3.0.5 on 2024-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_customer_orderplaced_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'mans clothes'), ('W', 'womans clothes'), ('S', 'shoes'), ('C', 'cosmetic product')], max_length=2),
        ),
    ]
