# Generated by Django 3.0.5 on 2024-04-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240414_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Esewa', 'Esewa'), ('khalti', 'khalti')], default='Cash On Delivery', max_length=20),
        ),
    ]
