# Generated by Django 5.0.4 on 2024-06-20 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
