# Generated by Django 5.0.4 on 2024-06-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_latestproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('esewa', 'esewa'), ('khalti', 'khalti')], default='Cash On Delivery', max_length=20),
        ),
    ]
