# Generated by Django 5.0.4 on 2024-06-21 07:28

import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_orderplaced_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[app.validators.validate_mobile_number]),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(choices=[('Achham', 'achham'), ('Arghakhanchi', 'arghakhanchi'), ('Baglung', 'baglung'), ('Baitadi', 'baitadi'), ('Bajhang', 'bajhang'), ('Bajura', 'bajura'), ('Banke', 'banke'), ('Bara', 'bara'), ('Bardiya', 'bardiya'), ('Bhaktapur', 'bhaktapur'), ('Bhojpur', 'bhojpur'), ('Chitwan', 'chitwan'), ('Dadeldhura', 'dadeldhura'), ('Dailekh', 'dailekh'), ('Dang', 'dang'), ('Darchula', 'darchula'), ('Dhading', 'dhading'), ('Dhankuta', 'dhankuta'), ('Dhanusha', 'dhanusha'), ('Dolakha', 'dolakha'), ('Dolpa', 'dolpa'), ('Doti', 'doti'), ('Gorkha', 'gorkha'), ('Gulmi', 'gulmi'), ('Humla', 'humla'), ('Ilam', 'ilam'), ('Jajarkot', 'jajarkot'), ('Jhapa', 'jhapa'), ('Jumla', 'jumla'), ('Kailali', 'kailali'), ('Kalikot', 'kalikot'), ('Kanchanpur', 'kanchanpur'), ('Kapilvastu', 'kapilvastu'), ('Kaski', 'kaski'), ('Kathmandu', 'kathmandu'), ('Kavrepalanchok', 'kavrepalanchok'), ('Khotang', 'khotang'), ('Lalitpur', 'lalitpur'), ('Lamjung', 'lamjung'), ('Mahottari', 'mahottari'), ('Makwanpur', 'makwanpur'), ('Manang', 'manang'), ('Morang', 'morang'), ('Mugu', 'mugu'), ('Mustang', 'mustang'), ('Myagdi', 'myagdi'), ('Nawalparasi', 'nawalparasi'), ('Nuwakot', 'nuwakot'), ('Okhaldhunga', 'okhaldhunga'), ('Palpa', 'palpa'), ('Panchthar', 'panchthar'), ('Parbat', 'parbat'), ('Parsa', 'parsa'), ('Pyuthan', 'pyuthan'), ('Ramechhap', 'ramechhap'), ('Rasuwa', 'rasuwa'), ('Rautahat', 'rautahat'), ('Rolpa', 'rolpa'), ('Rukum', 'rukum'), ('Rupandehi', 'rupandehi'), ('Salyan', 'salyan'), ('Sankhuwasabha', 'sankhuwasabha'), ('Saptari', 'saptari'), ('Sarlahi', 'sarlahi'), ('Sindhuli', 'sindhuli'), ('Sindhupalchok', 'sindhupalchok'), ('Siraha', 'siraha'), ('Solukhumbu', 'solukhumbu'), ('Sunsari', 'sunsari'), ('Surkhet', 'surkhet'), ('Syangja', 'syangja'), ('Tanahun', 'tanahun'), ('Taplejung', 'taplejung'), ('Terhathum', 'terhathum'), ('Udayapur', 'udayapur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Province 1', 'koshi'), ('Province 2', 'madesh pradesh'), ('Bagmati', 'bagmati'), ('Gandaki', 'gandaki'), ('Lumbini', 'lumbini'), ('Karnali', 'karnali'), ('Sudurpashchim', 'sudur_pashchim')], max_length=50),
        ),
    ]
