# Generated by Django 5.0.4 on 2024-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default=96832, max_length=128),
            preserve_default=False,
        ),
    ]
