# Generated by Django 5.0.4 on 2024-06-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
