# Generated by Django 5.0.4 on 2024-07-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_otptoken_otp_code_productinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='ef6a7c', max_length=6),
        ),
    ]
