# Generated by Django 5.0.4 on 2024-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_otptoken_otp_code_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='c2e9d0', max_length=6),
        ),
    ]
