# Generated by Django 5.0.4 on 2024-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_product_average_rating_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(default='In Stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='a6fa59', max_length=6),
        ),
    ]
